import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "300",
    "400",
    "500",
    "600",
    "700",
    "800"
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
 children,
 params
}: {
 children: React.ReactNode;
 params: {locale:string};
}) {

 const messages = await getMessages();

  return (
  <html lang={params.locale} dir={params.locale === "ar" ? "rtl":"ltr"}>
    <body className={`${poppins.variable} `}>
    <NextIntlClientProvider messages={messages}>
          {children}
    </NextIntlClientProvider>
    </body>
  </html>
  );
}
