import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Toaster } from "react-hot-toast";
import { ReduxProvider } from "../redux/provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "300",
    "400",
    "500",
    "600",
    "700",
    "800"
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
 children,
 params
}: {
 children: React.ReactNode;
 params: Promise<{locale:string}>;
}) {

 const { locale } = await params;
 const messages = await getMessages();

  return (
  <html lang={locale} dir={locale === "ar" ? "rtl":"ltr"}>
    <body className={`${poppins.variable} `}>
    <NextIntlClientProvider messages={messages}>
      <ReduxProvider>
          {children}
          <Toaster />
      </ReduxProvider>
    </NextIntlClientProvider>
    </body>
  </html>
  );
}
